name: expense_tracker
description: A personal expense tracking application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # Firebase packages
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  
  # State management
  provider: ^6.0.5
  
  # Local storage
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  
  # UI related
  fl_chart: ^0.63.0
  intl: any
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  
  # Utility packages
  uuid: ^3.0.7
  connectivity_plus: ^4.0.2

  #language support
  easy_localization: ^3.0.3

  # local auth
  local_auth: ^2.3.0
  # Add this for Android support
  local_auth_android: any  
  # Add this for iOS support
  local_auth_darwin: any  
  # getx
  get: ^4.6.6
  # flutter_screen_lock
  flutter_screen_lock: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/